### ISSUE TITLE
settings in OpenCPN

### ISSUE THREAD

**Issue by Retep1972** [transmitterdan/AISconverter#1]
This is great stuff and just what I was looking for! Is there a readme available for the needed OpenCPN settings?

**Comment by transmitterdan** [comment]
In the Tools->Connections configuration create a connection as follows:

Type = Net
DataPort = 0.0.0.0:10110
Priority = 1
Parameters = UDP
Connection = Input
Filters = In: None, Out: None

Run the python script as follows:

python AISconverter.py DataSet2.txt localhost 10110 0.1

As soon as python starts then it will convert to AIS format and send the data from DataSet2.txt to OpenCPN which should be listening on port 10110. If you have turned on Auto Follow (F2) then you will see the chart move to the location of the ship near Taiwan.
