### ISSUE TITLE
Multiple target presentation

### ISSUE THREAD

**Issue by Retep1972** [transmitterdan/AISconverter#2]
I have created a textfile with multiple ships. But OpenCPN only shows the first one. I think I created the proper text file. Context: I'm getting frequent position updates from target from a rest service and want to show them on OpenCPM as AIS target. therefore I'm creating a textfile every 3 sec and input this in the AIS convertor. In the end I want to input is directly from the rest server. 

As attachement my file I created. 
[sample1.txt](https://github.com/transmitterdan/AISconverter/files/659337/sample1.txt)

**Comment by Retep1972** [comment]
In normal text editor it did not look like something was wrong. When looking more closely a new line was missing.

**Comment by transmitterdan** [comment]
@Retep1972 

This was actually a bug. It is fixed now so that a blank line is just ignored and the conversion continues with the next line in the data file.

**Comment by Retep1972** [comment]
Hi,

Works like a charme now. 
Can you give me some advice, I'm a little bit stuck.. My restservice is creating a new "sample.txt" file every 2 seconds. So I want to read the sample.txt file in a loop with a 2 seconds delay.

I thought this worked best in the parse_line function. So after the if len(LineText)==0, I insterted:
f.close (close the excisting sample file)
time.sleep(2)
f = open('C:\etc sample.txt')
parse_line(f) 

I would assume that it would start to parse the new txt file but instead it's doing nothing.

Could you give me a hint? 

Best regards,
Peter 

Verzonden vanaf Yahoo! Mail voor Windows 8

Van: transmitterdan<notifications@github.com>
Verzonden: ‎zo, ‎01‎.‎jan‎.‎2017 om ‎05‎:‎36
Aan: transmitterdan/AISconverter <AISconverter@noreply.github.com>
Cc: Retep1972 <pjwhooijmans@yahoo.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [transmitterdan/AISconverter] Multiple target presentation (#2)

@Retep1972This was actually a bug. It is fixed now so that a blank line is just ignored and the conversion continues with the next line in the data file.—

**Comment by Retep1972** [comment]
Hi,

Never mind my question. I go it working. Python is unforgiven  with typo's.. I think your programme is great! Thank you very much.

Best regards,
Peter

Verzonden vanaf Yahoo! Mail voor Windows 8

Van: P. Hooijmans<pjwhooijmans@yahoo.com>
Verzonden: ‎di, ‎03‎.‎jan‎.‎2017 om ‎12‎:‎14
Aan: transmitterdan/AISconverter <reply@reply.github.com>
Onderwerp: Re: [transmitterdan/AISconverter] Multiple target presentation (#2)

Hi,

Works like a charme now. 
Can you give me some advice, I'm a little bit stuck.. My restservice is creating a new "sample.txt" file every 2 seconds. So I want to read the sample.txt file in a loop with a 2 seconds delay.

I thought this worked best in the parse_line function. So after the if len(LineText)==0, I insterted:
f.close (close the excisting sample file)
time.sleep(2)
f = open('C:\etc sample.txt')
parse_line(f) 

I would assume that it would start to parse the new txt file but instead it's doing nothing.

Could you give me a hint? 

Best regards,
Peter 

Verzonden vanaf Yahoo! Mail voor Windows 8

Van: transmitterdan<notifications@github.com>
Verzonden: ‎zo, ‎01‎.‎jan‎.‎2017 om ‎05‎:‎36
Aan: transmitterdan/AISconverter<AISconverter@noreply.github.com>
Cc: Retep1972 <pjwhooijmans@yahoo.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [transmitterdan/AISconverter] Multiple target presentation (#2)

@Retep1972This was actually a bug. It is fixed now so that a blank line is just ignored and the conversion continues with the next line in the data file.—
