### ISSUE TITLE
Ships name and thanks. (Forum txt copy)

### ISSUE THREAD

**Issue by Hakansv** [transmitterdan/AISconverter#3]
Dan..
Many thanks for your "AISconverter" function. You've saved me from "reinventing the wheel". For my radar ARPA simulation tests I needed a function to have AIS targets running beside my ship. (We're testing a method to not draw an ARPA target where an AIS is already present.) Now I use my "send_NMEA_COM app to produce a text file for your Python app. Thanks to your code it works great. It's some bite tricks to produce the AVDM message.
If you by a change would be into your AISconverter code again and get an idea to add ships name I would very much appreciate to be noted by for example a @Hakansv tag on the commit. (I've not yet been into Python coding. For me it's full time to learn some C++. )
Again - Thanks
Håkan

**Comment by Hakansv** [comment]
Dan..
My ask for ships names in your code was slightly hasty. For my needs it was sufficient and easier for all to add a name in MMSINAME.CSV.  So, pls close this issue if you like.
But your method works great.
![ais](https://cloud.githubusercontent.com/assets/7202854/21539761/02e3ee84-cdaa-11e6-988f-77efe6a488fc.PNG)

Again; thanks/Håkan

**Comment by transmitterdan** [comment]
@Hakansv 

I have added the ability to include ship names for class B targets. Also, have added ability to send data via STDIN or pipe so it can be used in a real time situation. AISconverter can act as a "filter" to convert the output of some other process in real time and send the AIS data to OpenCPN or other AIS display device that is accessible via IP.
