### ISSUE TITLE
No Class B tracks?

### ISSUE THREAD

**Issue by Retep1972** [transmitterdan/AISconverter#4]
I'm using the same text format as the sample file  but the sample file shows a track on OpenCPN but my text files does not. I realy see no difference, what do I miss?? In the AIS list it shows the name of the track but does not display a track symbol on the chart.

I'm now stuck with this for days, please help..

[sample4.txt](https://github.com/transmitterdan/AISconverter/files/925058/sample4.txt)

**Comment by transmitterdan** [comment]
Well, there are a few things about your file that cause problems. First, each message must be terminated in a newline. You are putting 4 messages together on one line. Start each TYPE= on a new line.

Secondly, you are repeating the exact same coordinates for the type 18 messages. It requires at least 2 different coordinates to define a track. So make each lat/long different by some small amount if you want to see a track line.

Attached is your file and what I see in OpenCPN after adding newlines after each message. There will be no tracks shown until you provide different coordinates for multiple TYPE ="18" messages.

![screenshot](https://cloud.githubusercontent.com/assets/10525699/25084567/e21ebb88-2322-11e7-8698-da6fb34fd5a5.png)

[sample4a.txt](https://github.com/transmitterdan/AISconverter/files/925240/sample4a.txt)
