### ISSUE TITLE
Minor issues found

### ISSUE THREAD

**Issue by pa36651** [transmitterdan/AISconverter#5]
Hi, I am using AISconverter and has found the following issues/bugs.

1. Line 62. I think that the '1':33 shall be changed to '!':33
sixbitencoding = {'@':0,'A':1,'B':2,'C':3,'D':4,'E':5,'F':6,'G':7,'H':8,'I':9,'J':10,'K':11,'L':12,'M':13,'N':14,'O':15,
                  'P':16,'Q':17,'R':18,'S':19,'T':20,'U':21,'V':22,'W':23,'X':24,'Y':25,'Z':26,'[':27,'\\':28,']':29,'^':30,'_':31,
                  ' ':32,'1':33,'"':34,'#':35,'$':36,'%':37,'&':38,'\'':39,'(':40,')':41,'*':42,'+':43,',':44,'-':45,'.':46,'/':47,
'0':48,'1':49,'2':50,'3':51,'4':52,'5':53,'6':54,'7':55,'8':56,'9':57,':':58,';':59,'<':60,'=':61,'>':62,'?':63}

2. Line 246
aisnmea = '!' + aisnmea + '*' + '{:02x}'.format(checksum)
This checksum is printed in lower case. According to AIS standard the checksum shall be upp case. Some AIS decoders give error with lower case.
I changed to '{:02X}', and that fixed the issue.

/Petter

**Comment by transmitterdan** [comment]
Petter,

Thank you for the information. Master branch is updated with these changes.
