### ISSUE TITLE
Question AISconverter

### ISSUE THREAD

**Issue by gersmit** [transmitterdan/AISconverter#7]
Dear @transmitterdan,

My name is Ger from Holland. 
I live close to the harbour IJMuiden en found your program on Github.
This script give me more freedom to use data what i want to see.
The artikel is several year ago but hope you will help me out.
Your program work in Python 3 but:
How make an file containing lat, lon, ship_name, cours, heading
How do i read a file with data.
Can you tell me if it is possible to input data live from variable or how to use STdin or pipe?
I get message Exiting cleanly, what is that mean?

Thanks in advance for an answer to help me out

Greetings Ger, Beverwijk, Holland

**Comment by gersmit** [comment]
Dear @transmitterdan,
I can read the file but get noting on screen in Opencpn.
Only my own coordinates i made before.
Data is oke (attachement)
Can you explane to me what i am doing wrong.

Thanks Ger
![opencpn](https://user-images.githubusercontent.com/38345229/110127663-2f919a00-7dc6-11eb-8b81-1b7475164d1d.JPG)

**Comment by transmitterdan** [comment]
Hello Ger,

There is an example file in the git repository.  It demonstrates how to format the text file to contain LAT, LON, SHIP NAME and everything else.

The program can read a text file from hard drive or it can read from STDIN.  Because STDIN can be from a PIPE then it can also read data from another program.  The program does not read from a an IP address.  For that you would probably need to create a PIPE using something like CURL to retrieve the data from an IP address and then send it to STDOUT.

The program says "Exiting cleanly" when it has reached the end of the text file with no errors.  If you want to continuously repeat the file over and over you can use the watch program on Linux.  For Windows there isn't a watch utility.

If you send your text file I can see try to find why it does not show anything on the screen.

Cheers,
Dan

**Comment by gersmit** [comment]
@transmitterdan , hi Dan,

Thanks for the fast replay, answer and explain.
It is working now an dsee the triangle on the screen but now i make an txt file from an script that use web scrape from Vesselfinder.
Can you tell me what is  obligated like lat, lon, speed?

And if it is possible can you explane to me how use the pipe construction in Python, because i am not an expert with Python.

Thanks in advance
Gr. Ger

**Comment by transmitterdan** [comment]
Ger,

I do not know how the Vesselfinder data looks.  So I cannot tell you how to convert that format data.

Only type 1 or type 18 messages are mandatory.  But you will not see vessel information for pleasure vessels unless type 24 message is available.  For commercial ship only type 1 message is needed.

If you have a program that prints to stdout data in the format shown in the example text file and that program is called, for example, "getvesseldata" then you can pipe that into AIS converter like this:

 getvesseldata | python AISconverter.py --dest=localhost --port=10110 --sleep=0.0001

In the above command the getvesseldata program prints to stdout, then python reads stdout and converts that data to NMEA format and sends it as UDP data stream to the local computer on port 10110.

Dan

**Comment by gersmit** [comment]
@transmitterdan, your explain help me to get the data, thanks for that.
One small problem:
When i run data as speed, course or heading with value after the point i get error, data is not loading.
When i make speed etc. round value, (attachement) it works fine. Do you no what is the problem, do i have to make integer or something?

stdout, stdin = i use two program, one to get data from vesselfinder.com and your program AISconverter.
The first programm write to an txt file, is it very difficult to connect the first program with your program to run both automaticly with stdin, stdoud?

The attachement is an test.

Thanks and g
![ais_vessel](https://user-images.githubusercontent.com/38345229/110473121-78a36000-80de-11eb-821e-eae2cf069463.JPG)
reetings Ger

**Comment by transmitterdan** [comment]
Gers,

The speed in the file is multiplied by 10 times the actual speed.  In other words, SPEED=124 means the speed is really 12.4.  So all of the values for angles and speed must be integer.  This is part of the NMEA format.

If you have a program that writes to STDOUT then you can connect that program to AISconverter.py using the pipe | feature.  If the program is "dataprogram" then you use the | symbol to pass STDOUT to STDIN.  In that case, do not use any file name. 
Example:

dataprogram | python AISconverter.py --dest=localhost --port=10110 --sleep=0.001

**Comment by gersmit** [comment]
Dear Dan, 
What is the advantage of STDOUT, STDIN?
I now start AISconverter from the first script with os.system ('python aisconverter.py ship_postions.txt').
Small qustion:
In my area some ships have no name, at least Vesselfinder.com doesn't show them. I enter this manually and it is also visible in the file ship_positions.txt but does not show it in Opencpn (see attachement). Do you know why this is and how I can fix this?

Ger
![ais_vessel pont](https://user-images.githubusercontent.com/38345229/110690119-d7063680-81e3-11eb-8af6-0dffe1acec2e.JPG)

**Comment by transmitterdan** [comment]
Hello Ger,

I can't tell what is happening from a screen shot.  Please attach a copy of the data file to a message here.  I will take a look at the file.

Dan

**Comment by gersmit** [comment]
Hi Dan, Thanks foor taking an look.
In the attachement the file that not show the ship_name "pont 8".

Ger
[ship_positions.txt](https://github.com/transmitterdan/AISconverter/files/6121201/ship_positions.txt)

**Comment by transmitterdan** [comment]
Ger,

You cannot put everything in one message.  AIS does not work that way.  AIS has specific message types for different types of data.  Each different message type must be on its own line.

Look carefully at the example file.  You  must create your text lines like the example file.  Look at each message TYPE to see what data each message type can contain.  Each message type must contain exactly the same data as in the example file.  You cannot add extra data to a message in AIS, it will not work.  Neither can you leave out any data in any message type.  Read again the README.MD file where it explains which message types the program can use.  It cannot use any other message type at this time.

**Comment by gersmit** [comment]
Dan,
Strange, the message working oke by me.
I see the 3 ships and get also the info.
The only thing is, i can not see the name of the "pont 8", the other names i can see good..
But i try as you say. That way worked before good.
I think when i put all in the same row i can see better for error.

Gr. Ger

**Comment by gersmit** [comment]
Dan, excuse.
I change the row as in your data file and i can see the name now.
i'm sorry i want to know better than the master

Greetings Ger

**Comment by transmitterdan** [comment]
Ger,

I do not mind answering questions.  If you have all your questions answered please close this issue.  But you can ask as many questions as you like.

Dan

**Comment by gersmit** [comment]
Hi Dan,
Small question before closing issue:
How to handle with Length / Beam or other data, do i have to put that on the same row as Course / Speed?
Do you no is there is an other program than Opencpn to plot all the data in Linux (Raspberry Pi).
I wil more flexibility with colors for ships, text etc.

Ger

**Comment by transmitterdan** [comment]
These data are defined for message type 5.  Currently AISconverter does not handle message type 5.  I am working on that.  It will take me a little time because I have other work i need to do right now.

**Comment by gersmit** [comment]
Oke Dan, thanks for sofar and work is more important.
I close the issue and wait for changes on Github.

Ger

**Comment by transmitterdan** [comment]
@gersmit 

I added the Type 5 message to AISconverter.  Now you can include vessel information such as length, beam, draught, and any other data in AIS message type 5.  Also, I added the rate of turn (ROT) field to message type 1.

**Comment by gersmit** [comment]
@transmitterdan 
Great Dan, thanks.
Thank you for doing it so quickly, but do the important things in life first. I have time as a pensioner.

Thanks again and I try it, greetings
Ger

**Comment by transmitterdan** [comment]
I was making a lot of other improvements anyway so I pushed this intermediate version which just added type 5. 

In next version most of the items in each message will have default values. But that isn't too important.

**Comment by gersmit** [comment]
👍

**Comment by gersmit** [comment]
Hi Dan,
Small question.
Can i use the type 5 messages in the same row or do i need to make a new row?
TYPE="18" MMSI="244699000" SPEED="0" LON="4.58480" LAT="52.45810" COURSE="44"  HEADING="44" CHANNEL="A" TIMESTAMP="2021-17-03T14:04:02"
TYPE="24" MMSI="306117000" PART_NO="0" CHANNEL="A" SHIP_NAME="SIERRA LAUREL"

Ger

**Comment by transmitterdan** [comment]
Get,

Yes, put all type 5 parameters on one line. The program will create 2 NMEA messages as required. 

Best regards,
Dan Dickey

**Comment by transmitterdan** [comment]
Ger, Each type message must be on a row alone.  You cannot put two TYPE= statements on the same row of text.  For each Type message you need one row per message. Dan Sent from Mail for Windows 10 From: gersmitSent: Wednesday, March 17, 2021 9:41 AMTo: transmitterdan/AISconverterCc: transmitterdan; MentionSubject: Re: [transmitterdan/AISconverter] Question AISconverter (#7) Hi Dan,Small question.Can i use the type 5 messages in the same row or do i need to make a new row?TYPE="18" MMSI="244699000" SPEED="0" LON="4.58480" LAT="52.45810" COURSE="44" HEADING="44" CHANNEL="A" TIMESTAMP="2021-17-03T14:04:02"TYPE="24" MMSI="306117000" PART_NO="0" CHANNEL="A" SHIP_NAME="SIERRA LAUREL"Ger—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by gersmit** [comment]
Hi Dan,
When i wil enter lenght and beam than Opencpn is not showing the data
What do i do wrong. With type 24 en 18 it works oke, when i use type5 row, no data.
**what information is required?**

TYPE="24" MMSI="244112000" PART_NO="0" CHANNEL="A" SHIP_NAME=""
 TYPE="18" MMSI="244112000" SPEED="0" LON="4.59498" LAT="52.45835" COURSE="322" HEADING="322" CHANNEL="A" TIMESTAMP="2021-22-03T12:46:58"
 TYPE="5" MMSI="244112000" REPEAT="3" CHANNEL="A" LENGHT="17" BEAM="4"
TYPE="24" MMSI="244130293" PART_NO="0" CHANNEL="A" SHIP_NAME=""
 TYPE="18" MMSI="244130293" SPEED="0" LON="4.59550" LAT="52.46456" COURSE="0" HEADING="0" CHANNEL="A" TIMESTAMP="2021-22-03T12:46:58"
 TYPE="5" MMSI="244130293" REPEAT="3" CHANNEL="A" LENGHT="56" BEAM="8"

**Comment by transmitterdan** [comment]
Type 5 does not have LENGTH or BEAM values.  Type 5 uses 4 numbers to describe the dimensions of the vessel.  Distance to bow, distance to stern, distance to port and finally distance to starboard.  These distances are relative to the location of the GPS antenna supplying GNSS data to the AIS transmitter.  It is possible to compute length and beam from these values (length = distance to bow + distance to stern) & (beam = distance to port + distance to starboard).  But the Type=5 message has no field for LENGTH or BEAM.

(edited to change 24 to 5)

**Comment by transmitterdan** [comment]
Ger,

I'm sorry I mistyped 24 instead of 5.  It is Type 5 message that has 4 numbers to describe the ship geometry.

**Comment by gersmit** [comment]
Oke Dan, thanks, now i understand it.
I am going to try again.
👍
